### ISSUE TITLE
manticore-extra requires  manticore-columnar-lib (>= 1.16.1) but only 1.15.4 available

### ISSUE THREAD

**Issue by barryhunter** [manticoresoftware/executor#31]
Not sure where else to report this.   
  
Trying to install manticore-extra so can test buddy.   
  
     apt install manticore-extra  
  
gets  
  
      The following packages have unmet dependencies:  
       manticore-extra : Depends: manticore-columnar-lib (>= 1.16.1) but it is not going to be installed  
  
ok, so run  
  
     apt install manticore-columnar-lib  
  
Installs everything (ok, I guess) [already have a running manticore instance from the helm chart in a pod. ]  
  
    The following additional packages will be installed:  
      manticore manticore-common manticore-dev manticore-icudata-65l manticore-server manticore-server-core manticore-tools  
  
But ends up being 1.15.4  
  
     Unpacking manticore-columnar-lib (1.15.4-220522-2fef34e) ...  
  
So now  
```  
apt install manticore-extra  
 manticore-extra : Depends: manticore-columnar-lib (>= 1.16.1) but 1.15.4-220522-2fef34e is to be installed  
```  
  
```  
$ apt search manticore-extra  
Sorting... Done  
Full Text Search... Done  
manticore-extra/buster 0.6.2-23012604-d95e43e all  
  Manticore extra package that includes executor and columnar lib  
```  
The repo was freshly added  
```  
$ wget https://repo.manticoresearch.com/manticore-repo.noarch.deb  
  
$ dpkg -i manticore-repo.noarch.deb  
Selecting previously unselected package manticore-repo.  
(Reading database ... 14324 files and directories currently installed.)  
Preparing to unpack manticore-repo.noarch.deb ...  
Unpacking manticore-repo (0.0.4) ...  
Setting up manticore-repo (0.0.4) ...  
/var/lib/dpkg/info/manticore-repo.postinst: 2: /var/lib/dpkg/info/manticore-repo.postinst: gpg: not found  
  
  
```

**Comment by barryhunter** [comment]
Ok, found https://github.com/manticoresoftware/homebrew-manticore/blob/685080d25f9a9e56db9fd168e76a388c07a97a81/Formula/manticore-extra.rb 
which suggests the 'extra' package, might just be a wrapper around 'exercutor' and columnar libs. 

And indeed can just install it directly... 
```
 apt install manticore-executor
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  manticore-executor
0 upgraded, 1 newly installed, 0 to remove and 55 not upgraded.
Need to get 7750 kB of archives.
After this operation, 29.6 MB of additional disk space will be used.
Get:1 http://repo.manticoresearch.com/repository/manticoresearch_buster buster/main amd64 manticore-executor amd64 0.6.2-23012605-d95e43e [7750 kB]
Fetched 7750 kB in 0s (16.6 MB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package manticore-executor.
(Reading database ... 14531 files and directories currently installed.)
Preparing to unpack .../manticore-executor_0.6.2-23012605-d95e43e_amd64.deb ...
Unpacking manticore-executor (0.6.2-23012605-d95e43e) ...
Setting up manticore-executor (0.6.2-23012605-d95e43e) ...
```

For my purposes that is ok, only want executor (for running 'bin/query/' from buddy) anyway.

**Comment by githubmanticore** [comment]
➤ Sergey Nikolaev commented:
 

 
This is because the new tools buddy, backup, executor, extra have not been released yet and are available as dev packages only which requires you to use dev packages for the other packages too. Here's how you get the dev packages via APT https://manual.manticoresearch.com/dev/Installation/Debian_and_Ubuntu#Development-packages
