### ISSUE TITLE
Mysqli support in dev executor

### ISSUE THREAD

**Issue by djklim87** [manticoresoftware/executor#43]
- [x] Need to add `mysqli` support in `dev executor` builds

- [x] Update executor in CLT test kit `/usr/bin/manticore-executor-dev`

**Comment by donhardman** [comment]
Waiting for the pull request to be finished: https://github.com/manticoresoftware/executor/pull/44

**Comment by donhardman** [comment]
The pull with deps update: https://github.com/manticoresoftware/manticoresearch/pull/1558
Also can download 1.0.7 dev version from the release on github

**Comment by djklim87** [comment]
Yes, now mysqli is able in the latest test kit
