### ISSUE TITLE
RdKafka extension support

### ISSUE THREAD

**Issue by djklim87** [manticoresoftware/executor#51]
For supporting reading from Kafka sources we need to add [rdkafka](https://github.com/arnaud-lb/php-rdkafka) extension to our executor

I am concerned that It also needs C++ lib [rdkafka](https://github.com/confluentinc/librdkafka) and this dependency can break all executors binary

**Comment by donhardman** [comment]
Implemented and merged to the main: https://github.com/manticoresoftware/executor/pull/52
